import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import i18next from 'eslint-plugin-i18next';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/** Attributes whose value a person reads or a screen reader speaks. */
const SPOKEN_ATTRIBUTES =
  'JSXAttribute[name.name=/^(aria-label|alt|placeholder|title|label|aria-valuetext|aria-roledescription|aria-placeholder)$/]';

export default tseslint.config(
  {
    ignores: ['**/dist/**', '**/node_modules/**', '**/coverage/**', '**/.turbo/**', 'data/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'error',
    },
  },
  {
    files: ['apps/cli/**', 'apps/web/scripts/**'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
    plugins: { 'react-hooks': reactHooks, 'react-refresh': reactRefresh, i18next },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // Every visible string goes through the message catalogue (docs/I18N.md).
      'i18next/no-literal-string': ['error', { mode: 'jsx-text-only' }],
      // That rule checks text children only, so the strings a screen reader
      // speaks but nobody sees would otherwise bypass the catalogue.
      'no-restricted-syntax': [
        'error',
        // Three shapes, because a literal reaches an attribute three ways:
        // bare, wrapped in braces, or written as a template. A literal deeper
        // than that is an argument to something — t(...) among them — and is
        // not the string being rendered.
        //
        // `label` is here because TableCell's is the column heading a phone
        // prints beside every value, so it is as visible as any other string.
        {
          selector: `${SPOKEN_ATTRIBUTES} > Literal`,
          message: 'A string a reader sees or hears goes through the catalogue: use t(...).',
        },
        {
          selector: `${SPOKEN_ATTRIBUTES} > JSXExpressionContainer > Literal`,
          message: 'A string a reader sees or hears goes through the catalogue: use t(...).',
        },
        {
          selector: `${SPOKEN_ATTRIBUTES} > JSXExpressionContainer > TemplateLiteral`,
          message: 'A string a reader sees or hears goes through the catalogue: use t(...).',
        },
      ],
    },
  },
  {
    // Generated by shadcn/ui and kept in its shape, so a component added later
    // with the generator needs no edits. Exporting a variant helper beside its
    // component is that shape.
    files: ['apps/web/src/components/ui/**/*.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  prettier,
);
