import { z } from 'zod';

/**
 * Ledger event types (DATA_MODEL.md section 22). Only material changes are events.
 */
export const EventType = z.enum([
  'workspace.created',
  'user.created',
  'membership.created',
  'membership.updated',
  'agent.created',
  'agent.updated',
  'agent.credential_issued',
  'agent.credential_revoked',
  'permission.granted',
  'permission.revoked',
  'policy.rule_changed',
  'command.denied',
  'category.proposed',
  'category.created',
  'category.updated',
  'category.moved',
  'category.merged',
  'category.archived',
  'knowledge.proposed_create',
  'knowledge.proposed_update',
  'knowledge.proposed_delete',
  'knowledge.proposed_supersede',
  'knowledge.created',
  'knowledge.updated',
  'knowledge.moved',
  'knowledge.superseded',
  'knowledge.deleted',
  'knowledge.restored',
  'knowledge.purged',
  'relation.created',
  'relation.removed',
  'proposal.approved',
  'proposal.rejected',
  'proposal.edited_and_approved',
  'proposal.withdrawn',
  'proposal.conflict',
  'sync.started',
  'sync.completed',
  'sync.expired',
  'summary.generated',
  'summary.marked_stale',
  'attachment.uploaded',
  'attachment.extracted',
  'webhook.changed',
  'integrity.check_completed',
]);
export type EventType = z.infer<typeof EventType>;

export const ObjectType = z.enum([
  'workspace',
  'user',
  'membership',
  'actor',
  'agent',
  'credential',
  'permission',
  'policy_rule',
  'category',
  'knowledge_item',
  'relation',
  'proposal',
  'sync_session',
  'attachment',
  'webhook',
  'command',
  'integrity_check',
]);
export type ObjectType = z.infer<typeof ObjectType>;
