-- The unit of the index becomes a chunk (ADR 0020).
--
-- One row per item ranks titles well and is the wrong unit for a long
-- document: it matches on a sentence buried inside and cannot say where, and
-- an embedding of four thousand words is an average of everything the document
-- says. Nothing here is authoritative — the index is a projection of the
-- canonical files — so the old table is dropped rather than migrated, and the
-- server fills the new one on start the way it already fills gaps.
DROP TABLE IF EXISTS "search_documents";--> statement-breakpoint

CREATE TABLE "search_chunks" (
	"id" varchar(40) PRIMARY KEY NOT NULL,
	"knowledge_item_id" varchar(40) NOT NULL,
	"workspace_id" varchar(40) NOT NULL,
	-- The revision this was built from, so a stale row is recognisable.
	"revision_id" varchar(40) NOT NULL,
	"language" varchar(8) NOT NULL,
	-- Repeated on every chunk and weighted above the text: a query whose words
	-- are split between the title and a sentence in the middle of the body has
	-- to be able to match.
	"title" text NOT NULL,
	"ordinal" integer NOT NULL,
	"text" text NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "search_chunks_item_fk" FOREIGN KEY ("knowledge_item_id")
		REFERENCES "knowledge_items"("id") ON DELETE cascade,
	CONSTRAINT "search_chunks_workspace_fk" FOREIGN KEY ("workspace_id")
		REFERENCES "workspaces"("id") ON DELETE cascade,
	CONSTRAINT "search_chunks_ordinal_check" CHECK ("ordinal" >= 0)
);--> statement-breakpoint

-- Generated by the database, so a chunk cannot be indexed under one text and
-- searched under another.
ALTER TABLE "search_chunks" ADD COLUMN "document_tsv" tsvector
	GENERATED ALWAYS AS (
		pg_catalog.setweight(public.knoverge_tsvector("language", "title"), 'A')
		|| pg_catalog.setweight(public.knoverge_tsvector("language", "text"), 'B')
	) STORED;--> statement-breakpoint
ALTER TABLE "search_chunks" ADD COLUMN "simple_tsv" tsvector
	GENERATED ALWAYS AS (
		pg_catalog.setweight(public.knoverge_tsvector('simple', "title"), 'A')
		|| pg_catalog.setweight(public.knoverge_tsvector('simple', "text"), 'B')
	) STORED;--> statement-breakpoint

CREATE UNIQUE INDEX "search_chunks_item_ordinal_idx"
	ON "search_chunks" ("knowledge_item_id", "ordinal");--> statement-breakpoint
CREATE INDEX "search_chunks_document_tsv_idx" ON "search_chunks" USING gin ("document_tsv");--> statement-breakpoint
CREATE INDEX "search_chunks_simple_tsv_idx" ON "search_chunks" USING gin ("simple_tsv");--> statement-breakpoint
CREATE INDEX "search_chunks_workspace_idx" ON "search_chunks" ("workspace_id");
