import { sql } from 'drizzle-orm';
import { customType, index, pgTable, text, varchar } from 'drizzle-orm/pg-core';

import { id, timestampTz } from './common.ts';
import { knowledgeItems } from './knowledge.ts';
import { workspaces } from './workspaces.ts';

/** PostgreSQL's own type; the database fills these columns, never a query. */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => 'tsvector',
});

/**
 * What makes canonical content findable.
 *
 * A projection, not a source: Git holds the knowledge, this holds the index
 * over it, and `knoverge db reindex` rebuilds it from the files
 * (`DATA_MODEL.md` section 28). Nothing here is authoritative, so losing it
 * costs a rebuild rather than any knowledge.
 *
 * The vectors are generated columns, so an item cannot be indexed under one
 * text and searched under another. The language decides the configuration,
 * which is what makes a Russian item stem as Russian.
 *
 * One row per item. Milestone 6 adds search chunks for long items, and the
 * body here becomes the fallback for one short enough not to be split.
 */
export const searchDocuments = pgTable(
  'search_documents',
  {
    knowledgeItemId: id('knowledge_item_id')
      .primaryKey()
      .references(() => knowledgeItems.id, { onDelete: 'cascade' }),
    workspaceId: id('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** The revision this was built from, so a stale row is recognisable. */
    revisionId: id('revision_id').notNull(),
    language: varchar('language', { length: 8 }).notNull(),
    title: text('title').notNull(),
    body: text('body').notNull(),
    updatedAt: timestampTz('updated_at').notNull(),
    // Generated by the database, so a query never writes them and an item
    // cannot be indexed under one text and searched under another.
    //
    // One vector with the title weighted above the body, because separate
    // vectors per field cannot answer a query whose words are split between
    // them. The simple one is the same text unstemmed, which is what finds an
    // item written in a language the query was not parsed in.
    documentTsv: tsvector('document_tsv').generatedAlwaysAs(
      sql`pg_catalog.setweight(public.knoverge_tsvector("language", "title"), 'A')
          || pg_catalog.setweight(public.knoverge_tsvector("language", "body"), 'B')`,
    ),
    simpleTsv: tsvector('simple_tsv').generatedAlwaysAs(
      sql`pg_catalog.setweight(public.knoverge_tsvector('simple', "title"), 'A')
          || pg_catalog.setweight(public.knoverge_tsvector('simple', "body"), 'B')`,
    ),
  },
  (table) => [
    index('search_documents_document_tsv_idx').using('gin', table.documentTsv),
    index('search_documents_simple_tsv_idx').using('gin', table.simpleTsv),
    index('search_documents_workspace_idx').on(table.workspaceId),
  ],
);
