import { sql } from 'drizzle-orm';
import {
  customType,
  index,
  integer,
  pgTable,
  text,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/pg-core';

import { id, timestampTz } from './common.ts';
import { knowledgeItems } from './knowledge.ts';
import { workspaces } from './workspaces.ts';

/** PostgreSQL's own type; the database fills these columns, never a query. */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => 'tsvector',
});

/**
 * What makes canonical content findable.
 *
 * A projection, not a source: Git holds the knowledge, this holds the index
 * over it, and `knoverge db reindex` rebuilds it from the files
 * (`DATA_MODEL.md` section 28). Nothing here is authoritative, so losing it
 * costs a rebuild rather than any knowledge.
 *
 * One row per chunk (ADR 0020). The title is repeated on each one and weighted
 * above the text, so a query whose words are split between the title and a
 * sentence in the middle of the body can still match.
 */
export const searchChunks = pgTable(
  'search_chunks',
  {
    id: id('id').primaryKey(),
    knowledgeItemId: id('knowledge_item_id')
      .notNull()
      .references(() => knowledgeItems.id, { onDelete: 'cascade' }),
    workspaceId: id('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    /** The revision this was built from, so a stale row is recognisable. */
    revisionId: id('revision_id').notNull(),
    language: varchar('language', { length: 8 }).notNull(),
    title: text('title').notNull(),
    /** Zero-based position in the item, and stable for the same text. */
    ordinal: integer('ordinal').notNull(),
    text: text('text').notNull(),
    updatedAt: timestampTz('updated_at').notNull(),
    // Generated by the database, so a chunk cannot be indexed under one text
    // and searched under another. The language decides the configuration,
    // which is what makes a Russian chunk stem as Russian. The simple one is
    // the same text unstemmed, which is what finds an exact word — an
    // identifier, a product name — whatever language either side is in.
    documentTsv: tsvector('document_tsv').generatedAlwaysAs(
      sql`pg_catalog.setweight(public.knoverge_tsvector("language", "title"), 'A')
          || pg_catalog.setweight(public.knoverge_tsvector("language", "text"), 'B')`,
    ),
    simpleTsv: tsvector('simple_tsv').generatedAlwaysAs(
      sql`pg_catalog.setweight(public.knoverge_tsvector('simple', "title"), 'A')
          || pg_catalog.setweight(public.knoverge_tsvector('simple', "text"), 'B')`,
    ),
  },
  (table) => [
    uniqueIndex('search_chunks_item_ordinal_idx').on(table.knowledgeItemId, table.ordinal),
    index('search_chunks_document_tsv_idx').using('gin', table.documentTsv),
    index('search_chunks_simple_tsv_idx').using('gin', table.simpleTsv),
    index('search_chunks_workspace_idx').on(table.workspaceId),
  ],
);
